version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres          # Uncomment this when using postgres.
    networks:
      - fullstack

  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

  other-postgres:
    image: postgres:latest
    container_name: other_db_postgres
    environment:
      - POSTGRES_USER=${OTHER_DB_USER}  
      - POSTGRES_PASSWORD=${OTHER_DB_PASSWORD}
      - POSTGRES_DB=${OTHER_DB_NAME}
      - DATABASE_HOST=${OTHER_DB_HOST} 
    ports:
      - '5433:5432'
    volumes:
      - other_database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    
volumes:
  api:
  database_postgres:                  
  other_database_postgres:

networks:
  fullstack:
    driver: bridge
